import {
  Type,
  IngredientSpec,
  StandardProduct,
  GuaranteedProductRecipe,
  BallProductRecipe,
} from './Types';

export const ingredientSpecTable: readonly IngredientSpec[] = [
  {name: 'バグメモリ', type: 'むし', score: 40},
  {name: 'ねばりのかぎづめ', type: 'むし', score: 26},
  {name: 'ぎんのこな', type: 'むし', score: 10},
  {name: 'きれいなぬけがら', type: 'むし', score: 8},
  {name: 'タンガのみ', type: 'むし', score: 4},
  {name: 'あまいミツ', type: 'むし', score: 2},
  /* {name: 'ナゾのみ', type: 'むし', score: 0}, */
  {name: 'ダークメモリ', type: 'あく', score: 40},
  {name: 'あやしいパッチ', type: 'あく', score: 32},
  {name: 'じゃくてんほけん', type: 'あく', score: 30},
  {name: 'するどいツメ', type: 'あく', score: 26},
  {name: 'からぶりほけん', type: 'あく', score: 24},
  {name: 'こうかくレンズ', type: 'あく', score: 22},
  {name: 'フォーカスレンズ', type: 'あく', score: 22},
  {name: 'くろいメガネ', type: 'あく', score: 14},
  {name: 'ねらいのまと', type: 'あく', score: 14},
  {name: 'ピントレンズ', type: 'あく', score: 12},
  {name: 'しめつけバンド', type: 'あく', score: 8},
  {name: 'タラプのみ', type: 'あく', score: 6},
  {name: 'レンブのみ', type: 'あく', score: 6},
  {name: 'ナモのみ', type: 'あく', score: 4},
  {name: 'イアのみ', type: 'あく', score: 4},
  {name: 'くろぼんぐり', type: 'あく', score: 0},
  {name: 'ドラゴンメモリ', type: 'ドラゴン', score: 40},
  {name: 'しんかのきせき', type: 'ドラゴン', score: 32},
  {name: 'いのちのたま', type: 'ドラゴン', score: 20},
  {name: 'りゅうのキバ', type: 'ドラゴン', score: 18},
  {name: 'りゅうのウロコ', type: 'ドラゴン', score: 18},
  {name: 'カセキのリュウ', type: 'ドラゴン', score: 10},
  {name: 'ダイマックスアメ', type: 'ドラゴン', score: 6},
  {name: 'ジャポのみ', type: 'ドラゴン', score: 6},
  {name: 'バンジのみ', type: 'ドラゴン', score: 4},
  {name: 'ハバンのみ', type: 'ドラゴン', score: 4},
  {name: 'エレクトロメモリ', type: 'でんき', score: 40},
  {name: 'でんきだま', type: 'でんき', score: 20},
  {name: 'じしゃく', type: 'でんき', score: 20},
  {name: 'じゅうでんち', type: 'でんき', score: 14},
  {name: 'カセキのトリ', type: 'でんき', score: 10},
  {name: 'エレキシード', type: 'でんき', score: 8},
  {name: 'かみなりのいし', type: 'でんき', score: 6},
  {name: 'ソクノのみ', type: 'でんき', score: 4},
  {name: 'モモンのみ', type: 'でんき', score: 2},
  {name: 'あおぼんぐり', type: 'でんき', score: 0},
  {name: 'フェアリーメモリ', type: 'フェアリー', score: 40},
  {name: 'ベリーアメざいく', type: 'フェアリー', score: 30},
  {name: 'よつばアメざいく', type: 'フェアリー', score: 30},
  {name: 'おはなアメざいく', type: 'フェアリー', score: 30},
  {name: 'ハートアメざいく', type: 'フェアリー', score: 30},
  {name: 'リボンアメざいく', type: 'フェアリー', score: 30},
  {name: 'スターアメざいく', type: 'フェアリー', score: 30},
  {name: 'いちごアメざいく', type: 'フェアリー', score: 30},
  {name: 'ホイップポップ', type: 'フェアリー', score: 26},
  {name: 'においぶくろ', type: 'フェアリー', score: 20},
  {name: 'ひかりのこな', type: 'フェアリー', score: 14},
  {name: 'ミストシード', type: 'フェアリー', score: 8},
  {name: 'アッキのみ', type: 'フェアリー', score: 6},
  {name: 'つきのいし', type: 'フェアリー', score: 6},
  {name: 'ひかりのいし', type: 'フェアリー', score: 6},
  {name: 'ロゼルのみ', type: 'フェアリー', score: 4},
  {name: 'せいれいプレート', type: 'フェアリー', score: 2},
  {name: 'ももぼんぐり', type: 'フェアリー', score: 0},
  {name: 'ファイトメモリ', type: 'かくとう', score: 40},
  {name: 'たつじんのおび', type: 'かくとう', score: 32},
  {name: 'ヨロイこうせき', type: 'かくとう', score: 28},
  {name: 'きょうせいギプス', type: 'かくとう', score: 26},
  {name: 'こだわりハチマキ', type: 'かくとう', score: 20},
  {name: 'パワーアンクル', type: 'かくとう', score: 20},
  {name: 'パワーバンド', type: 'かくとう', score: 20},
  {name: 'パワーベルト', type: 'かくとう', score: 20},
  {name: 'パワーリスト', type: 'かくとう', score: 20},
  {name: 'パワーウエイト', type: 'かくとう', score: 20},
  {name: 'くろおび', type: 'かくとう', score: 14},
  {name: 'ちからのハチマキ', type: 'かくとう', score: 14},
  {name: 'きあいのハチマキ', type: 'かくとう', score: 12},
  {name: 'きあいのタスキ', type: 'かくとう', score: 12},
  {name: 'ぼうごパット', type: 'かくとう', score: 12},
  {name: 'カムラのみ', type: 'かくとう', score: 12},
  {name: 'ネコブのみ', type: 'かくとう', score: 6},
  {name: 'リゾチウム', type: 'かくとう', score: 4},
  {name: 'インドメタシン', type: 'かくとう', score: 4},
  {name: 'ヨプのみ', type: 'かくとう', score: 4},
  {name: 'マックスアップ', type: 'かくとう', score: 4},
  {name: 'ブロムヘキシン', type: 'かくとう', score: 4},
  {name: 'タウリン', type: 'かくとう', score: 4},
  {name: 'キトサン', type: 'かくとう', score: 4},
  {name: 'ヒメリのみ', type: 'かくとう', score: 2},
  {name: 'ファイヤーメモリ', type: 'ほのお', score: 40},
  {name: 'もくたん', type: 'ほのお', score: 32},
  {name: 'レッドカード', type: 'ほのお', score: 16},
  {name: 'かえんだま', type: 'ほのお', score: 14},
  {name: 'あついいわ', type: 'ほのお', score: 12},
  {name: 'ほのおのいし', type: 'ほのお', score: 6},
  {name: 'たいようのいし', type: 'ほのお', score: 6},
  {name: 'フィラのみ', type: 'ほのお', score: 4},
  {name: 'オッカのみ', type: 'ほのお', score: 4},
  {name: 'クラボのみ', type: 'ほのお', score: 2},
  {name: 'あかぼんぐり', type: 'ほのお', score: 0},
  {name: 'フライングメモリ', type: 'ひこう', score: 40},
  {name: 'ふうせん', type: 'ひこう', score: 20},
  {name: 'ばんのうがさ', type: 'ひこう', score: 20},
  {name: 'するどいくちばし', type: 'ひこう', score: 10},
  {name: 'サンのみ', type: 'ひこう', score: 10},
  {name: 'せいしんのハネ', type: 'ひこう', score: 6},
  {name: 'ちりょくのハネ', type: 'ひこう', score: 6},
  {name: 'ウブのみ', type: 'ひこう', score: 6},
  {name: 'たいりょくのハネ', type: 'ひこう', score: 6},
  {name: 'きんりょくのハネ', type: 'ひこう', score: 6},
  {name: 'きれいなハネ', type: 'ひこう', score: 6},
  {name: 'ていこうのハネ', type: 'ひこう', score: 6},
  {name: 'しゅんぱつのハネ', type: 'ひこう', score: 6},
  {name: 'バコウのみ', type: 'ひこう', score: 4},
  {name: 'ラムのみ', type: 'ひこう', score: 2},
  {name: 'ゴーストメモリ', type: 'ゴースト', score: 40},
  {name: 'れいかいのぬの', type: 'ゴースト', score: 32},
  {name: 'のろいのおふだ', type: 'ゴースト', score: 26},
  {name: 'きよめのおふだ', type: 'ゴースト', score: 24},
  {name: 'ビビリだま', type: 'ゴースト', score: 12},
  {name: 'イバンのみ', type: 'ゴースト', score: 10},
  {name: 'やみのいし', type: 'ゴースト', score: 6},
  {name: 'カシブのみ', type: 'ゴースト', score: 4},
  {name: 'マゴのみ', type: 'ゴースト', score: 4},
  {name: 'あやしいおこう', type: 'ゴースト', score: 2},
  {name: 'グラスメモリ', type: 'くさ', score: 40},
  {name: 'あまーいりんご', type: 'くさ', score: 30},
  {name: 'すっぱいりんご', type: 'くさ', score: 30},
  {name: 'かおるキノコ', type: 'くさ', score: 24},
  {name: 'たべのこし', type: 'くさ', score: 20},
  {name: 'ながねぎ', type: 'くさ', score: 18},
  {name: 'いじっぱりミント', type: 'くさ', score: 16},
  {name: 'ずぶといミント', type: 'くさ', score: 16},
  {name: 'ゆうかんミント', type: 'くさ', score: 16},
  {name: 'おだやかミント', type: 'くさ', score: 16},
  {name: 'しんちょうミント', type: 'くさ', score: 16},
  {name: 'おとなしいミント', type: 'くさ', score: 16},
  {name: 'せっかちミント', type: 'くさ', score: 16},
  {name: 'わんぱくミント', type: 'くさ', score: 16},
  {name: 'ようきミント', type: 'くさ', score: 16},
  {name: 'のうてんきミント', type: 'くさ', score: 16},
  {name: 'さみしがりミント', type: 'くさ', score: 16},
  {name: 'おっとりミント', type: 'くさ', score: 16},
  {name: 'ひかえめミント', type: 'くさ', score: 16},
  {name: 'むじゃきミント', type: 'くさ', score: 16},
  {name: 'やんちゃミント', type: 'くさ', score: 16},
  {name: 'れいせいミント', type: 'くさ', score: 16},
  {name: 'うっかりやミント', type: 'くさ', score: 16},
  {name: 'のんきミント', type: 'くさ', score: 16},
  {name: 'なまいきミント', type: 'くさ', score: 16},
  {name: 'まじめミント', type: 'くさ', score: 16},
  {name: 'おくびょうミント', type: 'くさ', score: 16},
  {name: 'おおきなキノコ', type: 'くさ', score: 14},
  {name: 'メンタルハーブ', type: 'くさ', score: 14},
  {name: 'きせきのタネ', type: 'くさ', score: 14},
  {name: 'しろいハーブ', type: 'くさ', score: 14},
  {name: 'チイラのみ', type: 'くさ', score: 12},
  {name: 'パワフルハーブ', type: 'くさ', score: 10},
  {name: 'くっつきバリ', type: 'くさ', score: 10},
  {name: 'きゅうこん', type: 'くさ', score: 8},
  {name: 'おおきなねっこ', type: 'くさ', score: 8},
  {name: 'グラスシード', type: 'くさ', score: 8},
  {name: 'ひかりごけ', type: 'くさ', score: 8},
  {name: 'リーフのいし', type: 'くさ', score: 6},
  {name: 'ガラナツのえだ', type: 'くさ', score: 4},
  {name: 'リンドのみ', type: 'くさ', score: 4},
  {name: 'チーゴのみ', type: 'くさ', score: 2},
  {name: 'おはなのおこう', type: 'くさ', score: 2},
  {name: 'ちいさなキノコ', type: 'くさ', score: 2},
  {name: 'みどぼんぐり', type: 'くさ', score: 0},
  {name: 'グラウンドメモリ', type: 'じめん', score: 40},
  {name: 'でかいきんのたま', type: 'じめん', score: 38},
  {name: 'かけたポット', type: 'じめん', score: 36},
  {name: 'われたポット', type: 'じめん', score: 30},
  {name: 'やわらかいすな', type: 'じめん', score: 20},
  {name: 'ふといホネ', type: 'じめん', score: 18},
  {name: 'きんのたま', type: 'じめん', score: 16},
  {name: 'あつぞこブーツ', type: 'じめん', score: 16},
  {name: 'ズアのみ', type: 'じめん', score: 12},
  {name: 'きちょうなホネ', type: 'じめん', score: 12},
  {name: 'グランドコート', type: 'じめん', score: 12},
  {name: 'ほしのすな', type: 'じめん', score: 8},
  {name: 'ロメのみ', type: 'じめん', score: 6},
  {name: 'シュカのみ', type: 'じめん', score: 4},
  {name: 'キーのみ', type: 'じめん', score: 2},
  {name: 'アイスメモリ', type: 'こおり', score: 40},
  {name: 'すいせいのかけら', type: 'こおり', score: 34},
  {name: 'とけないこおり', type: 'こおり', score: 14},
  {name: 'リュガのみ', type: 'こおり', score: 12},
  {name: 'つめたいいわ', type: 'こおり', score: 12},
  {name: 'カセキのクビナガ', type: 'こおり', score: 10},
  {name: 'ゆきだま', type: 'こおり', score: 8},
  {name: 'こおりのいし', type: 'こおり', score: 6},
  {name: 'ザクロのみ', type: 'こおり', score: 6},
  {name: 'ヤチェのみ', type: 'こおり', score: 4},
  {name: 'ナナシのみ', type: 'こおり', score: 2},
  {name: 'とくせいカプセル', type: 'ノーマル', score: 40},
  {name: 'ポイントマックス', type: 'ノーマル', score: 40},
  {name: 'ポイントアップ', type: 'ノーマル', score: 38},
  {name: 'おまもりこばん', type: 'ノーマル', score: 32},
  {name: 'アップグレード', type: 'ノーマル', score: 30},
  {name: 'スピードパウダー', type: 'ノーマル', score: 28},
  {name: 'せんせいのツメ', type: 'ノーマル', score: 26},
  {name: 'シルクのスカーフ', type: 'ノーマル', score: 22},
  {name: 'こだわりスカーフ', type: 'ノーマル', score: 20},
  {name: 'しあわせタマゴ', type: 'ノーマル', score: 20},
  {name: 'ぼうじんゴーグル', type: 'ノーマル', score: 10},
  {name: 'ノーマルジュエル', type: 'ノーマル', score: 8},
  {name: 'ホズのみ', type: 'ノーマル', score: 4},
  {name: 'まんぷくおこう', type: 'ノーマル', score: 2},
  {name: 'こううんのおこう', type: 'ノーマル', score: 2},
  {name: 'しろぼんぐり', type: 'ノーマル', score: 0},
  {name: 'ポイズンメモリ', type: 'どく', score: 40},
  {name: 'どくバリ', type: 'どく', score: 32},
  {name: 'ねがいのかたまり', type: 'どく', score: 28},
  {name: 'けむりだま', type: 'どく', score: 22},
  {name: 'ガラナツブレス', type: 'どく', score: 18},
  {name: 'どくどくだま', type: 'どく', score: 14},
  {name: 'ヤタピのみ', type: 'どく', score: 12},
  {name: 'くろいヘドロ', type: 'どく', score: 10},
  {name: 'タポルのみ', type: 'どく', score: 6},
  {name: 'ビアーのみ', type: 'どく', score: 4},
  {name: 'ゴールドスプレー', type: 'どく', score: 2},
  {name: 'オレンのみ', type: 'どく', score: 2},
  {name: 'むしよけスプレー', type: 'どく', score: 2},
  {name: 'シルバースプレー', type: 'どく', score: 2},
  {name: 'ふしぎなアメ', type: 'エスパー', score: 40},
  {name: 'サイキックメモリ', type: 'エスパー', score: 40},
  {name: 'あかいいと', type: 'エスパー', score: 28},
  {name: 'ルームサービス', type: 'エスパー', score: 24},
  {name: 'こだわりメガネ', type: 'エスパー', score: 20},
  {name: 'ひかりのねんど', type: 'エスパー', score: 20},
  {name: 'パワーレンズ', type: 'エスパー', score: 20},
  {name: 'まがったスプーン', type: 'エスパー', score: 18},
  {name: 'けいけんアメXL', type: 'エスパー', score: 10},
  {name: 'スターのみ', type: 'エスパー', score: 10},
  {name: 'ものしりメガネ', type: 'エスパー', score: 10},
  {name: 'けいけんアメL', type: 'エスパー', score: 8},
  {name: 'サイコシード', type: 'エスパー', score: 8},
  {name: 'めざめのいし', type: 'エスパー', score: 6},
  {name: 'けいけんアメM', type: 'エスパー', score: 6},
  {name: 'マトマのみ', type: 'エスパー', score: 6},
  {name: 'けいけんアメS', type: 'エスパー', score: 4},
  {name: 'ウタンのみ', type: 'エスパー', score: 4},
  {name: 'けいけんアメXS', type: 'エスパー', score: 2},
  {name: 'のんきのおこう', type: 'エスパー', score: 2},
  {name: 'きよめのおこう', type: 'エスパー', score: 2},
  {name: 'オボンのみ', type: 'エスパー', score: 2},
  {name: 'ロックメモリ', type: 'いわ', score: 40},
  {name: 'ゴツゴツメット', type: 'いわ', score: 26},
  {name: 'プロテクター', type: 'いわ', score: 24},
  {name: 'かわらずのいし', type: 'いわ', score: 20},
  {name: 'ほしのかけら', type: 'いわ', score: 20},
  {name: 'かたいいし', type: 'いわ', score: 14},
  {name: 'まんまるいし', type: 'いわ', score: 12},
  {name: 'さらさらいわ', type: 'いわ', score: 12},
  {name: 'こうこうのしっぽ', type: 'いわ', score: 10},
  {name: 'ミクルのみ', type: 'いわ', score: 10},
  {name: 'かるいし', type: 'いわ', score: 8},
  {name: 'ヨロギのみ', type: 'いわ', score: 4},
  {name: 'ウィのみ', type: 'いわ', score: 4},
  {name: 'がんせきおこう', type: 'いわ', score: 2},
  {name: 'ぎんのおうかん', type: 'はがね', score: 40},
  {name: 'きんのおうかん', type: 'はがね', score: 40},
  {name: 'スチールメモリ', type: 'はがね', score: 40},
  {name: 'おうじゃのしるし', type: 'はがね', score: 32},
  {name: 'メタルコート', type: 'はがね', score: 24},
  {name: 'メトロノーム', type: 'はがね', score: 22},
  {name: 'とつげきチョッキ', type: 'はがね', score: 20},
  {name: 'だっしゅつボタン', type: 'はがね', score: 16},
  {name: 'だっしゅつパック', type: 'はがね', score: 16},
  {name: 'くろいてっきゅう', type: 'はがね', score: 16},
  {name: 'メタルパウダー', type: 'はがね', score: 14},
  {name: 'やすらぎのすず', type: 'はがね', score: 14},
  {name: 'リリバのみ', type: 'はがね', score: 4},
  {name: 'くちたたて', type: 'はがね', score: 2},
  {name: 'くちたけん', type: 'はがね', score: 2},
  {name: 'ウオーターメモリ', type: 'みず', score: 40},
  {name: 'おだんごしんじゅ', type: 'みず', score: 30},
  {name: 'きれいなウロコ', type: 'みず', score: 26},
  {name: 'かいがらのすず', type: 'みず', score: 14},
  {name: 'おおきなしんじゅ', type: 'みず', score: 12},
  {name: 'しめったいわ', type: 'みず', score: 12},
  {name: 'のどスプレー', type: 'みず', score: 12},
  {name: 'カセキのサカナ', type: 'みず', score: 10},
  {name: 'しんぴのしずく', type: 'みず', score: 10},
  {name: 'しんじゅ', type: 'みず', score: 6},
  {name: 'みずのいし', type: 'みず', score: 6},
  {name: 'イトケのみ', type: 'みず', score: 4},
  {name: 'カゴのみ', type: 'みず', score: 2},
  {name: 'うしおのおこう', type: 'みず', score: 2},
  {name: 'さざなみのおこう', type: 'みず', score: 2},
  {name: 'きぼんぐり', type: 'みず', score: 0},
];

// prettier-ignore
export const standardProductTable: ReadonlyArray< {
  type: Type;
  productTableByType: ReadonlyArray<StandardProduct | StandardProduct[]>;
}> = [
  { type: 'ノーマル', productTableByType: ['ふるいたてる','ゆびをふる','こらえる','きあいだめ','ねごと','さわぐ','のしかかり','トライアタック','バトンタッチ','アンコール','みがわり','つるぎのまい','ハイパーボイス','ぎんのおうかん','ポイントアップ'] },
  { type: 'かくとう', productTableByType: ['けたぐり','はどうだん','ちからのハチマキ','ねがいのかたまり','ビルドアップ','きしかいせい','きょうせいギプス','ボディプレス','たつじんのおび','きあいだま','ばかぢから','インファイト','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'ひこう', productTableByType: ['きれいなハネ','するどいくちばし','おおきなキノコ','ねがいのかたまり','ふうせん','からぶりほけん','ねばりのかぎづめ','ふうせん','じゃくてんほけん','ぼうふう','すいせいのかけら','ブレイブバード','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'どく', productTableByType: ['くろいヘドロ','どくどくだま','ベノムトラップ','ねがいのかたまり','どくびし','けむりだま','どくづき','スピードパウダー','どくバリ','ヘドロばくだん','ヘドロウェーブ','ダストシュート','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'じめん', productTableByType: ['ほしのすな','まきびし','おおきなキノコ','ねがいのかたまり','ひかりのねんど','ドリルライナー','だいちのちから','グランドコート','おだんごしんじゅ','10まんばりき','すいせいのかけら','じしん','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'いわ', productTableByType: ['かるいし','まんまるいし','かたいいし','ねがいのかたまり','かわらずのいし','プロテクター','ゴツゴツメット','パワージェム','ねがいのかたまり','しんかのきせき','ステルスロック','ストーンエッジ','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'むし', productTableByType: ['シザークロス','きゅうけつ','ひかりのこな','ねがいのかたまり','ぎんのこな','かおるキノコ','むしのさざめき','きれいなぬけがら','おだんごしんじゅ','かふんだんご','すいせいのかけら','メガホーン','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'ゴースト', productTableByType: ['あやしいおこう','ビビリだま','ねらいのまと','ねがいのかたまり','ほしのかけら','かおるキノコ','きよめのおふだ','のろいのおふだ','われたポット','れいかいのぬの','すいせいのかけら','シャドーボール','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'はがね', productTableByType: ['アイアンテール','てっぺき','メタルパウダー','ねがいのかたまり','ばんのうがさ','メタルコート','ジャイロボール','とつげきチョッキ','ヘビーボンバー','おまもりこばん','ラスターカノン','アイアンヘッド','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'ほのお', productTableByType: ['ヒートスタンプ','かえんだま','ブレイズキック','ねがいのかたまり','かえんほうしゃ','かおるキノコ','ねっぷう','レッドカード','だいもんじ','もくたん','フレアドライブ','オーバーヒート','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'みず', productTableByType: ['うしおのおこう','なみのり','かいがらのすず','ねがいのかたまり','たきのぼり','アクアブレイク','きれいなウロコ','しんぴのしずく','おだんごしんじゅ','だくりゅう','ねっとう','ハイドロポンプ','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'くさ', productTableByType: ['グラスシード','タネばくだん','しろいハーブ','ねがいのかたまり','くさむすび','リーフブレード','エナジーボール','きゅうこん','おだんごしんじゅ','パワーウィップ','すいせいのかけら','リーフストーム','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'でんき', productTableByType: ['エレキシード','エレキボール','じゅうでんち','ねがいのかたまり','じしゃく','ワイルドボルト','アップグレード','でんきだま','おだんごしんじゅ','あやしいパッチ','10まんボルト','かみなり','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'エスパー', productTableByType: ['こうそくいどう','みらいよち','スキルスワップ','アシストパワー','コスモパワー','サイドチェンジ','サイコショック','しねんのずつき','ドわすれ','トリック','めいそう','サイコファング','サイコキネシス','ぎんのおうかん','ポイントアップ'] },
  { type: 'こおり', productTableByType: ['ゆきだま','つめたいいわ','とけないこおり','ねがいのかたまり','ほしのかけら','かおるキノコ','するどいツメ','ゆきだま','おだんごしんじゅ','れいとうビーム','すいせいのかけら','ふぶき','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'ドラゴン', productTableByType: ['ドラゴンクロー','りゅうのキバ','おおきなキノコ','ねがいのかたまり','ほしのかけら','かおるキノコ','りゅうのウロコ','いのちのたま','りゅうのはどう','おうじゃのしるし','りゅうのまい','げきりん','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'あく', productTableByType: ['ちょうはつ','こうかくレンズ','わるだくみ','ねがいのかたまり','ほしのかけら','かおるキノコ','イカサマ','ピントレンズ','じごくづき','あくのはどう','かみくだく','DDラリアット','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
  { type: 'フェアリー', productTableByType: ['ほしのすな','ミストシード','おおきなキノコ','ねがいのかたまり','においぶくろ','ルームサービス','ホイップホップ','あかいいと',
                                            ['ベリーアメざいく','よつばアメざいく','おはなアメざいく','ハートアメざいく','いちごアメざいく'],
                                            'マジカルシャイン',
                                            ['リボンアメざいく','スターアメざいく','いちごアメざいく'],
                                            'じゃれつく','ふしぎなアメ','ぎんのおうかん','ポイントアップ'] },
];

export const guaranteedProductRecipeTable: readonly GuaranteedProductRecipe[] = [
  {triggerIngredient: 'ちいさなキノコ', product: 'おおきなキノコ'},
  {triggerIngredient: 'しんじゅ', product: 'おおきなしんじゅ'},
  {triggerIngredient: 'ほしのすな', product: 'ほしのかけら'},
  {triggerIngredient: 'おおきなキノコ', product: 'かおるキノコ'},
  {triggerIngredient: 'きんのたま', product: 'でかいきんのたま'},
  {triggerIngredient: 'おおきなしんじゅ', product: 'おだんごしんじゅ'},
  {triggerIngredient: 'ほしのかけら', product: 'すいせいのかけら'},
  {triggerIngredient: 'ふしぎなアメ', product: 'とくせいカプセル'},
  {triggerIngredient: 'ぎんのおうかん', product: 'きんのおうかん'},
];

export const ballProductRecipeTable: readonly BallProductRecipe[] = [
  {
    apricorn: 'くろぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ダークボール', rate: 6.25},
      {name: 'ゴージャスボール', rate: 6.25},
      {name: 'ヘビーボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'あおぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ダイブボール', rate: 6.25},
      {name: 'ネットボール', rate: 6.25},
      {name: 'ルアーボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'みどぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ハイパーボール', rate: 6.25},
      {name: 'ネストボール', rate: 6.25},
      {name: 'フレンドボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'ももぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ハイパーボール', rate: 6.25},
      {name: 'ヒールボール', rate: 6.25},
      {name: 'ラブラブボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'あかぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ハイパーボール', rate: 6.25},
      {name: 'リピートボール', rate: 6.25},
      {name: 'レベルボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'しろぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'プレミアボール', rate: 6.25},
      {name: 'タイマーボール', rate: 6.25},
      {name: 'スピードボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
  {
    apricorn: 'きぼんぐり',
    balls: [
      {name: 'モンスターボール', rate: 6.25},
      {name: 'スーパーボール', rate: 6.25},
      {name: 'ハイパーボール', rate: 6.25},
      {name: 'クイックボール', rate: 6.25},
      {name: 'ムーンボール', rate: 0.25},
      {name: 'サファリボール', rate: 0.025},
      {name: 'コンペボール', rate: 0.025},
    ],
  },
];
